### ISSUE TITLE
what does '--orphan' option do?

### ISSUE THREAD

**Issue by rjmk** [nofootnotes/harp-git#1]
In this section:

Create new branch "gh-pages"

``` git
$ git checkout --orphan gh-pages
```

what is the difference between 'checkout --orphan' and 'checkout -b'?

**Comment by Lukars** [comment]
--orphan
Create a new orphan branch, named <new_branch>, started from <start_point> and switch to it. The first commit made on this new branch will have no parents and it will be the root of a new history totally disconnected from all the other branches and commits.

-b 
This form switches branches by updating the index, working tree, and HEAD to reflect the specified branch.
