### ISSUE TITLE
Step 4 "Orphan" word not explained

### ISSUE THREAD

**Issue by cagarweyne** [nofootnotes/harp-git#3]
Step 4 in the instructions for setting up it says to create a new branch and the instruction after that: $ git checkout --orphan gh-pages uses the word "orphan" which is not explained. Is this a git keyword or something else?

**Comment by Lukars** [comment]
Orphan is one way of creating a new branch within your git repository. The other way to do this would be -b.

Here are the differences:

--orphan
Create a new orphan branch, named <new_branch>, started from <start_point> and switch to it. The first commit made on this new branch will have no parents and it will be the root of a new history totally disconnected from all the other branches and commits.

-b 
This form switches branches by updating the index, working tree, and HEAD to reflect the specified branch.
