### ISSUE TITLE
Error in command in step 5

### ISSUE THREAD

**Issue by rjmk** [nofootnotes/harp-git#9]
Hi,

I think the command in step 5 should read 'rm -rf' rather than 'git rm -rf'. Is this correct?

**Comment by ronanyeah** [comment]
According to the guide we followed, no!
http://harpjs.com/docs/deployment/github-pages

**Comment by rjmk** [comment]
OK, I get an error when I try this. I get a list of options for the command but nothing happens. Any tips? Cheers.

**Comment by rjmk** [comment]
I realised my mistake! According to the doc you linked the command should be 'git rm -rf .' rather than 'git rm -rf'.

**Comment by ronanyeah** [comment]
Fixed! Thanks for letting me know!
